---
 - hosts: ussd
   become: yes
   become_user: root



   vars_prompt:
     - name: Username
       prompt: enter user id that you want to unlock/password reset
       private: no

     - name: Password
       prompt: enter in a new password for your user account
       private: yes
       confirm: yes


   tasks:
    - name: Add the user 'X' with a bash shell, appending the group 'wheel' to the user's groups
      ansible.builtin.user:
        name:  "{{ Username | trim }}" 
        comment: "{{ Username | trim }}" 
        shell: /bin/bash
        groups: wheel
        append: yes

    - name: unlocking user id and generating new password
       ansible.builtin.user:
         name: "{{ Username | trim }}"
         password_lock: false
         password: "{{ Password | password_hash('sha512', 'mysecretsalt') }}"

