---
 - hosts: ussd
   become: yes

   vars_prompt:
     - name: Username
       prompt: enter user id that you want to unlock/password reset
       private: no

     - name: Password
       prompt: enter in a new password for your user account
       private: yes
       confirm: yes

   tasks:
     - name: unlocking user id and generating new password
       ansible.builtin.user:
         name: "{{ Username | trim }}"
         password_lock: false
         password: "{{ Password | password_hash('sha512', 'mysecretsalt') }}"

     - name: confirm user account is unlocked and can log in
       debug:
         msg:
           - "user account is unlocked and password has been reset"

